import type { IMicroserviceConfig } from "./types";
const makeMicroServiceConfig = (config: IMicroserviceConfig) => {
  config.theme.paletteTypes.default = true;
  return config;
};

const microServiceConfig = makeMicroServiceConfig({
  fonts: {
    Roboto: false,
    Beiruti: false,
    "Noto Nastaliq Urdu": false,
    Gulzar: false,
    Lalezar: false,
    Caveat: false,
  },
  iconFonts: {
    fontawesome: {
      brands: true,
      familyGroup: {
        classic: true,
        duotone: false,
        sharp: false,
        "sharp-duotone": false,
        chisel: false,
        etch: false,
        jelly: false,
        notdog: false,
        slab: false,
        thumbprint: false,
        utility: false,
        whiteboard: false,
      },
      weight: {
        solid: true,
        regular: false,
        light: false,
        thin: false,
      },
    },
  },
  theme: {
    themeModes: {
      dark: false,
      light: false,
      system: false,
    },
    paletteModes: {
      "darken-1": false,
      variant: false,
      bright: false,
      "lighten-1": false,
    },
    paletteColors: {
      background: false,
      surface: false,
      "on-surface": false,
      primary: false,
      "on-primary": false,
      secondary: false,
      "on-secondary": false,
      error: false,
      info: false,
      success: false,
      warning: false,
    },
    paletteTypes: {
      bumbleBee: false,
      winter: false,
      default: false,
      pastel: false,
      wood: false,
      neo: false,
      chroma: false,
      ocean: false,
      ston: false,
      neon: false,
      spring: false,
      fall: false,
      summer: false,
      water: false,
      hell: false,
      heaven: false,
      sunrise: false,
      moon: false,
      office: false,
      sport: false,
      company: false,
      jungle: false,
      food: false,
      coffee: false,
      cyberpunk: false,
      galaxy: false,
      retro: false,
      minimal: false,
    },
  },
  languages: {
    en: false,
    fa: false,
  },
  manifest: {
    name: "Dexterous Client",
    short_name: "Dexterous Client",
    icons: [
      {
        src: "/pwa/icons/icon-16x16.png",
        sizes: "16x16",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-32x32.png",
        sizes: "32x32",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-48x48.png",
        sizes: "48x48",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-72x72.png",
        sizes: "72x72",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-96x96.png",
        sizes: "96x96",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-128x128.png",
        sizes: "128x128",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-144x144.png",
        sizes: "144x144",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-152x152.png",
        sizes: "152x152",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-180x180.png",
        sizes: "180x180",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-192x192.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-256x256.png",
        sizes: "256x256",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-384x384.png",
        sizes: "384x384",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-512x512.png",
        sizes: "512x512",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-512x512.png",
        sizes: "512x512",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon-1024x1024.png",
        sizes: "1024x1024",
        type: "image/png",
      },
      {
        src: "/pwa/icons/icon.png",
        sizes: "512x512",
        type: "image/png",
      },
    ],
    screenshots: [
      {
        src: "/src/assets/media/pwa/Screenshot-376x320.png",
        sizes: "376x320",
        form_factor: "wide",
        type: "image/png",
      },
      {
        src: "/src/assets/media/pwa/screencapture-1170x2532_1.png",
        sizes: "1170x2532",
        form_factor: "narrow",
        type: "image/png",
      },
      {
        src: "/src/assets/media/pwa/screencapture-1170x2532_2.png",
        sizes: "1170x2532",
        form_factor: "narrow",
        type: "image/png",
      },
      {
        src: "/src/assets/media/pwa/screencapture-1170x2532_3.png",
        sizes: "1170x2532",
        form_factor: "narrow",
        type: "image/png",
      },
    ],
    background_color: "#078af7",
    theme_color: "#078af7",
    description: "Dexterous Client Application",
    id: "/?source=pwa",
    start_url: "/?source=pwa",
    display: "standalone",
    scope: "/",
    launch_handler: {
      client_mode: "focus-existing",
    },
    file_handlers: [],
    orientation: "any",
    display_override: [],
    dir: "ltr",
    lang: "",
    publicPath: "",
    related_applications: [],
    prefer_related_applications: false,
    protocol_handlers: [],
    shortcuts: [],
    categories: [],
    iarc_rating_id: "",
    scope_extensions: [],
  },
});
export default microServiceConfig;
