/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./components/layout/AuthLayout.vue')['default']
    BcAppDisable: typeof import('./components/base/BcAppDisable.vue')['default']
    BcCopyText: typeof import('./components/base/BcCopyText.vue')['default']
    BcIcon: typeof import('./components/base/BcIcon.vue')['default']
    BcTree: typeof import('./components/base/BcTree.vue')['default']
    FontProvider: typeof import('./components/provider/FontProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleTabChannelProvider: typeof import('./components/provider/SingleTabChannelProvider.vue')['default']
    Toast: typeof import('./components/base/Toast.vue')['default']
    ToastItem: typeof import('./components/base/ToastItem.vue')['default']
  }
}
