/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>, '/auth/forgotPassword' | '/auth/login' | '/auth/register'>,
    '/auth/forgotPassword': RouteRecordInfo<'/auth/forgotPassword', '/auth/forgotPassword', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/admin/': RouteRecordInfo<'/dashboard/admin/', '/dashboard/admin', Record<never, never>, Record<never, never>>,
    '/dashboard/operator/': RouteRecordInfo<'/dashboard/operator/', '/dashboard/operator', Record<never, never>, Record<never, never>>,
    '/example': RouteRecordInfo<'/example', '/example', Record<never, never>, Record<never, never>>,
    '/log': RouteRecordInfo<'/log', '/log', Record<never, never>, Record<never, never>, '/log/404' | '/log/[...path]' | '/log/forbidden'>,
    '/log/[...path]': RouteRecordInfo<'/log/[...path]', '/log/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/log/404': RouteRecordInfo<'/log/404', '/log/404', Record<never, never>, Record<never, never>>,
    '/log/forbidden': RouteRecordInfo<'/log/forbidden', '/log/forbidden', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/auth.vue': {
      routes: '/auth' | '/auth/forgotPassword' | '/auth/login' | '/auth/register'
      views: 'default'
    }
    'src/pages/auth/forgotPassword.vue': {
      routes: '/auth/forgotPassword'
      views: never
    }
    'src/pages/auth/login.vue': {
      routes: '/auth/login'
      views: never
    }
    'src/pages/auth/register.vue': {
      routes: '/auth/register'
      views: never
    }
    'src/pages/dashboard/index.vue': {
      routes: '/dashboard/'
      views: never
    }
    'src/pages/dashboard/admin/index.vue': {
      routes: '/dashboard/admin/'
      views: never
    }
    'src/pages/dashboard/operator/index.vue': {
      routes: '/dashboard/operator/'
      views: never
    }
    'src/pages/example.vue': {
      routes: '/example'
      views: never
    }
    'src/pages/log.vue': {
      routes: '/log' | '/log/[...path]' | '/log/404' | '/log/forbidden'
      views: 'default'
    }
    'src/pages/log/[...path].vue': {
      routes: '/log/[...path]'
      views: never
    }
    'src/pages/log/404.vue': {
      routes: '/log/404'
      views: never
    }
    'src/pages/log/forbidden.vue': {
      routes: '/log/forbidden'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
